# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fill_array3d
#' 
#' This function is just for Rcmip5 package when combine 3d array.
#' 
#' Note that if data types of \code{mat} and \code{newmat} are different, 
#' values in \code{mat} will be \strong{not replaced.}
#' 
#' @param mat A 3d Array.
#' @param newmat A 3d Array to fill \code{mat}.
#' @param i_start Integer, row of \code{mat} starting to fill.
#' @param j_start Integer, col of \code{mat} starting to fill.
#' @param k_start Integer, slice of \code{mat} starting to fill.
#' 
#' @references
#' [1] https://stackoverflow.com/questions/30969799/column-means-3d-matrix-cube-rcpp \cr
#' [2] https://stackoverflow.com/questions/34161593/how-to-replace-elements-of-a-matrix-in-c-with-values-from-another-matrix-usin \cr
#' 
#' @examples
#' mat    <- array(2, dim = c(3, 3, 3))
#' newmat <- array(1, dim = c(3, 3, 3))
#' fill_array3d(mat, newmat)
#' mat
#' 
#' @export
fill_array3d <- function(mat, newmat, i_start = 1L, j_start = 1L, k_start = 1L) {
    invisible(.Call(`_RcppArray_fill_array3d`, mat, newmat, i_start, j_start, k_start))
}

#' @name fill_matrix
#' @title fill_matrix
#' 
#' Replace sub matrix in rcpp format.
#' 
#' @rdname fill_matrix
#' @inheritParams fill_array3d
#' @param mat A matrix.
#' @param newmat A matrix to fill \code{mat}.
#' 
#' @examples
#' # mat   : ones matrix
#' # newmat: 1:16 matrix
#' 
#' ## 1. rcpp version
#' mat <- matrix(1, 6, 6)
#' newmat <- matrix(1:16, 4, 4)*1.0
#' fill_matrix_rcpp(mat, newmat)
#' mat
#' 
#' ## 2. RcppArmadillo version
#' mat <- matrix(1, 6, 6)
#' newmat <- matrix(1:16, 4, 4)
#' fill_matrix_arma(mat, newmat)
#' mat
NULL

#' @rdname fill_matrix
#' @export
fill_matrix_rcpp <- function(mat, newmat, i_start = 1L, j_start = 1L) {
    invisible(.Call(`_RcppArray_fill_matrix_rcpp`, mat, newmat, i_start, j_start))
}

#' @rdname fill_matrix
#' @export
fill_matrix_arma <- function(mat, newmat, i_start = 1L, j_start = 1L) {
    invisible(.Call(`_RcppArray_fill_matrix_arma`, mat, newmat, i_start, j_start))
}

